#!/usr/bin/python
#	vim:fileencoding=utf-8
# Check all live ebuilds for updates and rebuild them if necessary.
# (C) 2010 Michał Górny <gentoo@mgorny.alt.pl>
# Released under the terms of the 3-clause BSD license or the GPL-2 license.

import sys

from SmartLiveRebuild.core import Config, SmartLiveRebuild
from SmartLiveRebuild.cli import parse_options

def main(argv):
	# initialize config with defaults
	c = Config()

	# parse opts to get the config file
	(opts, args) = parse_options(argv)
	c.apply_optparse(opts)

	# do the config file parsing
	c.parse_configfiles()

	# and now reapply the options to override config file defaults
	c.apply_optparse(opts)

	return SmartLiveRebuild(c.get_options(), args)

if __name__ == '__main__':
	sys.exit(main(sys.argv))
