#!/usr/bin/python
#	vim:fileencoding=utf-8
# Check all live ebuilds for updates and rebuild them if necessary.
# (c) 2010 Michał Górny <gentoo@mgorny.alt.pl>
# Released under the terms of the 3-clause BSD license or the GPL-2 license.

import sys, os.path

try:
	from SmartLiveRebuild.cli import main
except ImportError:
	sys.path.insert(0, os.path.dirname(sys.argv[0]))
	from SmartLiveRebuild.cli import main

if __name__ == '__main__':
	sys.exit(main(sys.argv))
